### ISSUE TITLE
Add comment about GLSL shader picking

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/shader_version#64]
I'd like to have a comment explaining https://github.com/PistonDevelopers/shader_version/blob/master/src/glsl.rs#L54-L58

**Comment by Potpourri** [comment]
OpenGL since 3.20 in core profile don't support GLSL lower 1.50.

**Comment by bvssvni** [comment]
It that case, will it return `None`?

**Comment by Potpourri** [comment]
If there is no compatible shader, then return `None`.
