### ISSUE TITLE
Think about better names for the variants of the OpenGL version enum

### ISSUE THREAD

**Issue by bstrie** [PistonDevelopers/shader_version#71]
Currently the enum looks like this:
```rust
pub enum OpenGL {
    _2_0,
    _2_1,
    _3_0,
    _3_1,
    _3_2,
    _3_3,
    _4_0,
    _4_1,
    _4_2,
    _4_3,
    _4_4,
    _4_5
}
```
...and is used like `OpenGL::_3_2` in client code. I have some minor objections to this:

1. Typical Rust code uses letter case to help the reader understand what a particular identifier represents. These variants contain no letters, so it's difficult at a glance to tell what `OpenGL::_3_2` is.

2. Normally, one sees identifiers prefixed with underscores in Rust code only when the author wants to silence an "unused variable" warning.

3. The combination of symbols produces `::_`, which just looks pretty ugly. :)

Would it be worth considering an alternate naming scheme? Perhaps `OpenGL::V3_2`?

**Comment by bvssvni** [comment]
Could also change to `OpenGl` instead of `OpenGL` to be more consistent. `OpenGl::V3_2` seems nice.

**Comment by bvssvni** [comment]
- [ ] `OpenGl::_3_2` => `OpenGl::V3_2`
- [ ] `GLSL::_1_50` => `Glsl::V1_50`
- [ ] `GLSL::to_OpenGL` => `Glsl::to_opengl`

**Comment by bvssvni** [comment]
People on IRC want to keep `OpenGL`.
