### ISSUE TITLE
Implement FromStr for OpenGL enum

### ISSUE THREAD

**Issue by Boiethios** [PistonDevelopers/shader_version#78]
All is in the title. I can implement this myself and propose a merge, but I just wanted to know before if you would agree.

This would help for specifying an OpenGL version from command line, for example.

**Comment by bvssvni** [comment]
I agree.

**Comment by Boiethios** [comment]
https://github.com/PistonDevelopers/shader_version/pull/79

Is it OK for you?

**Comment by Boiethios** [comment]
#79
